# Railway 一键部署配置
# 官方文档: https://docs.railway.app/deploy/config-as-code

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
timeout = 300
interval = 300
